### ISSUE TITLE
Timeout error after updating to lighthouse 6.3.0

### ISSUE THREAD

**Issue by asendia** [erezrokah/lighthouse-layer#61]
Hi, I got this error after updating to lighthouse 6.3.0:
```
Mon, 31 Aug 2020 12:57:30 GMT status Connecting to browser
Mon, 31 Aug 2020 12:57:30 GMT status Resetting state with about:blank
Mon, 31 Aug 2020 12:58:00 GMT status Disconnecting from browser...
2020-08-31T12:58:00.801Z	ERROR Invoke Error 	{"errorType":"LHError","errorMessage":"PROTOCOL_TIMEOUT","code":"PROTOCOL_TIMEOUT","name":"LHError","friendlyMessage":"Waiting for DevTools protocol response has exceeded the allotted time. (Method: Network.enable)","lhrRuntimeError":true,"protocolMethod":"Network.enable","stack":["LHError: PROTOCOL_TIMEOUT","    at Timeout._onTimeout (/opt/nodejs/node_modules/lighthouse/lighthouse-core/gather/driver.js:352:21)","    at listOnTimeout (internal/timers.js:549:17)"," at processTimers (internal/timers.js:492:7)"]}
```

Additional note:
- AWS Lambda node 12.x
- I ran `yarn` & `yarn deploy` from macOS Catalina 10.15.6, will try to run from Linux later
- Last version that I tried successfully was lighthouse 6.1.1: https://github.com/erezrokah/lighthouse-layer/commit/eceb4914a0e7b4cda7f886ad5374396e044eea80

**Comment by asendia** [comment]
Update: I have tried running `yarn` & `yarn deploy` from Linux and still got same error. I guess build environment does not matter.

I also tried these commits with same result:
- aa305aeca07e0ed46947566dfdc142be72f15255
- 359c4934534bc9ace20a820659dcfca472192529 (lighthouse 6.2.0)
